sudo: required
language: node_js
dist: trusty
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
notifications:
  email:
    - svarghese@aconex.com
